// <auto-generated />
using BPT.Test.JBP.API.JWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPT.Test.JBP.API.JWT.Migrations
{
    [DbContext(typeof(BPTTestJBPAPIJWTContext))]
    partial class BPTTestJBPAPIJWTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPT.Test.JBP.API.JWT.Entities.LoginJWT", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("LoginJWT");

                    b.HasData(
                        new
                        {
                            Username = "Jorge",
                            Password = "PASSWORDJWT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
